[versions]
agp = "8.9.1"
coreTesting = "2.2.0"
kotlin = "2.1.0"
kotlinxCollectionsImmutable = "0.3.5"
kotlinxCoroutines = "1.10.1"
compose= "1.10.1"
gson = "2.11.0"
ksp = "2.1.0-1.0.29"
coil = "3.1.0"
mockitoCore = "5.2.0"
turbine = "1.1.0"
navigationCompose = "2.8.9"
composeBom = "2025.04.00"
material = "1.12.0"
koin = "4.0.0"
okhttpBrotli = "4.2.2"
room = "2.7.0"
kotlinxSerializationJson = "1.8.0"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-activity-compose = {group = "androidx.activity", name = "activity-compose", version.ref = "compose"}
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

turbine = { module = "app.cash.turbine:turbine", name = "turbine", version.ref = "turbine" }

squareup-okhttp-brotli = { module = "com.squareup.okhttp3:okhttp-brotli", version.ref = "okhttpBrotli" }
squareup-retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "gson" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

